---
name: "CI"

concurrency:
    group: ${{ github.head_ref || github.run_id }}
    cancel-in-progress: true

on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
  release:
    types: [published]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Docker meta
        id: meta
        if: ${{ inputs.publish == 'true' }}
        uses: docker/metadata-action@v5
        with:
          images: test/name
          tags:
            type=ref,event=tag
     
