---
name: "CI"

concurrency:
    group: ${{ github.head_ref || github.run_id }}
    cancel-in-progress: true

on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
  release:
    types: [published]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Select image tag based on event
        shell: bash
        run:
          if [[ '${{ github.event_name }}' == 'release' ]]; then
            echo "IMAGE_TAG=${{ github.ref_name }}" >> $GITHUB_ENV
          else
            echo "IMAGE_TAG=latest" >> $GITHUB_ENV
          fi
     
