---
name: "CI"

concurrency:
    group: ${{ github.head_ref || github.run_id }}
    cancel-in-progress: true

on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
  release:
    types: [published]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: test/name
          tags: |
            type=raw,value=latest
            type=ref,event=tag
     
